name 'hunner-haproxy_plugin'
version '1.0.0'
source 'git://github.com/hunner/mcollective-haproxy_plugin.git'
author 'Hunter Haugen'
license 'Apache 2.0'
summary 'Puppet module and mcollective agent for enabling/disabling haproxy balancer members'
description 'Puppet module and mcollective agent for enabling/disabling haproxy balancer members'
project_page 'https://github.com/hunner/mcollective-haproxy_plugin'
